apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flare-agent
  namespace: flare-agent
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  rules:
    - host: flare.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flare-agent
                port:
                  name: http
