apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flare-agent
  namespace: flare-agent
  labels:
    app: flare-agent
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: flare-agent
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s

